version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx/development
    container_name: my-collection-nginx
    volumes:
      - .:/app
    depends_on:
      - php
    ports:
      - "8081:80"
    networks:
      main:

  php:
    build:
      context: ./docker/php/development
    container_name: my-collection-php
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      main:

  database:
    build:
      context: ./docker/postgres/development
    container_name: my-collection-database
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "123123"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/_var/postgres/development:/docker-entrypoint-initdb.d
      - ./docker/_var/database:/var/lib/postgresql/data:rw
    ports:
      - "15435:5432"
    restart: on-failure
    networks:
      main:

  encore:
    build:
      context: ./docker/encore/development
    container_name: my-collection-encore
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["yarn", "dev-server", "--host=0.0.0.0"]

volumes:
  composer:
  database:

networks:
  main:
