version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx/development
    volumes:
      - .:/app
    depends_on:
      - php
    ports:
      - "8082:80"
    networks:
      main-net:
        ipv4_address: 172.27.0.4
      database:
      php:

  php:
    build:
      context: ./docker/php/development
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      php:

  database:
    build:
      context: ./docker/postgres/development
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.docker/postgres/development:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - "15434:5432"

  encore:
    build:
      context: ./docker/encore/development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["yarn", "dev-server", "--host=0.0.0.0"]

volumes:
  composer:
  database:

networks:
  main-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  database:
  php:
