version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx/development
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8082:80"
    networks:
      main-net:
        ipv4_address: 172.27.0.4
      database:
      php-fpm:
  php-fpm:
    build:
      context: ./docker/php-fpm/development
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      php-fpm:
  php-cli:
    build:
      context: ./docker/php-cli/development
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
  database:
    build:
      context: ./docker/postgres/development
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.docker/postgres/development:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data:rw
    ports:
      - "15434:5432"

volumes:
  composer:
  database:

networks:
  main-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  database:
  php-fpm:
