version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx/development
    container_name: my-collection-nginx
    volumes:
      - .:/app
    depends_on:
      - php
    ports:
      - "8082:80"
    networks:
      main-net:
        ipv4_address: 172.27.0.4
      php:

  php:
    build:
      context: ./docker/php/development
    container_name: my-collection-php
    volumes:
      - .:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
    ports:
      - "9000:9000"
    networks:
      php:
      database:

  database:
    build:
      context: ./docker/postgres/development
    container_name: my-collection-database
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "123123"
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /docker/_var/database
    volumes:
      - ./.docker/postgres/development:/docker-entrypoint-initdb.d
      - ./docker/_var/database:/var/lib/postgresql/data:rw
    ports:
      - "15434:5432"
    restart: on-failure
    networks:
      database:

  encore:
    build:
      context: ./docker/encore/development
    container_name: my-collection-encore
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["yarn", "dev-server", "--host=0.0.0.0"]

volumes:
  composer:
  database:

networks:
  main-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  database:
  php:
