parameters:
  app.token_ttl: 86400

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Tmdb\:
    resource: '../vendor/php-tmdb/api/lib/Tmdb/*'

  App\Domain\Service\Password\PasswordHasher:
    arguments:
      $salt: '%env(PASSWORD_SALT)%'

  App\Domain\Service\AccessToken\TokenFactory:
    arguments:
      $secret: '%env(SECRET_TOKEN_STRING)%'
      $tokenTtl: '%app.token_ttl%'

  App\Domain\Service\AccessToken\TokenValidator:
    arguments:
      $secret: '%env(SECRET_TOKEN_STRING)%'

  App\Adapter\Response\Core\Subscriber\ExceptionResponseEventSubscriber:
    arguments:
      $isShowInternalException: '%env(bool:SHOW_500_DETAIL_ERROR)%'

  App\Domain\Service\Mail\MailSender:
    arguments:
      $currentDomain: '%env(CURRENT_DOMAIN)%'
      $defaultFrom: '%env(MAIL_FROM)%'

  App\Infrastructure\TMDB\ClientFactory:
    arguments:
      $apiToken: '%env(TMDB_API_TOKEN)%'

  Tmdb\Client:
    factory: ['@App\Infrastructure\TMDB\ClientFactory', 'create']
